### ISSUE TITLE
Desktop vs Mobile

### ISSUE THREAD

**Issue by gi11es** [anniesullie/LCP_Examples#2]
There doesn't seem to be a Desktop vs Mobile distinction here. Is it both together (in which case they probably need to be separated), or just one of them? And what were the SpeedIndex parameters used? (connectivity, viewport size, etc.).

**Comment by anniesullie** [comment]
The original data was for mobile, but I added a desktop data set. I clarified the parameters in the intro pages:

Mobile:
 * Device: Emulated Moto G4
 * Connection: 3G
 * Viewport: 512 x 360px

Desktop:
 * Device: Linux VM
 * Connection: Cable
 * Viewport: 1200 x 1920px
