### ISSUE TITLE
Websites vs Single Page App

### ISSUE THREAD

**Issue by subrataashe** [anniesullie/LCP_Examples#3]
Is there a dataset that was correlated with single page apps for mobile and desktop wrt LCP
I would be interested to know how LCP correlates with FCP and DOM Interactive in these apps.

**Comment by anniesullie** [comment]
I didn't run this type of query, but it should be possible to do using the same HttpArchive dataset if we query by framework used. Would you want to see something like the top 3 (React, Vue, Angular)?

**Comment by subrataashe** [comment]
Sure, that would be a nice datapoint, may be top 5 would do.

**Comment by anniesullie** [comment]
I wrote up two queries that join the HttpArchive technologies mobile/desktop tables (which uses [Wappalyzer](https://www.wappalyzer.com/categories/javascript-frameworks) to detect frameworks) with the mobile/desktop performance data from HttpArchive. I used the frameworks React, Angular/AngularJS, Vue.js, Ember.js, and Svelte. Here are the correlations:

**Desktop**
First Paint: 0.5446894734254084
First Contentful Paint: 0.5941890322543536
DOM Interactive: 0.5622874943132267
Speed Index: 0.7712802357163386
Visual Complete: 0.7666792957532297
onload: 0.6187961116393658

**Mobile**
First Paint: 0.43525234391215356
First Contentful Paint: 0.4839232839812175
DOM Interactive: 0.43604022806028403
Speed Index: 0.7184553847001154
Visual Complete: 0.6782603085702824
onload: 0.48178446497131977

So overall the data is really similar; most correlated with Speed Index and least with first paint/first contentful paint/dom interactive. I didn't have time to plot everything; would that be helpful?

Also I missed the body background images part of your question above--that was a completely separate analysis than the correlation study, so this data doesn't include any information about body background images.

**Comment by subrataashe** [comment]
Sorry, I miss-typed background images in my question ( corrected it to LCP).

This data looks amazing! A couple of thoughts
1. Since the Pearson Correlation drops from 0.87 to 0.77 for Speed Index, did you see any non-linearity in the data? 
2. Is there a way to know which framework had the least and greatest correlation for LCP vs Speed Index?

**Comment by anniesullie** [comment]
I added a datastudio that breaks out the speed index correlations by framework, so you can dig in a bit more:

https://datastudio.google.com/c/u/0/reporting/1_PwnEK9dwLAsTKa6OtrpMPnSwTL0k9Zi/page/Wig8

Also the table should be public if you want to query it in bigquery, it's `lcp-analysis.HttpArchive_PerformanceMetrics.PerformanceMetrics_2019_10_01_DesktopFrameworks_WithApp`
